DOCKER_COMPOSE_DIR="/codespace/laradock"
DOCKER_COMPOSE_SERVICES="apache2 mysql php-fpm"
PHINX_PHP_CONTAINER="laradock_php-fpm_1"
PHINX_PROJECT_DIR="/var/www/famac-web-server"
PHINX_BINARY_PATH="$PHINX_PROJECT_DIR/vendor/bin/phinx"
PHINX_CONFIG_PATH="$PHINX_PROJECT_DIR/config/config-phinx.php"